# Generated by Django 5.0.6 on 2024-05-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.TextField()),
                ('equipment', models.TextField()),
                ('fault_type', models.TextField()),
                ('problem_description', models.TextField()),
                ('client', models.TextField()),
                ('status', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
