# Generated by Django 5.0.6 on 2024-05-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_ticketmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='equipment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='fault_type',
            field=models.TextField(blank=True),
        ),
    ]
