# Generated by Django 5.0.6 on 2024-05-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_ticketmodel_equipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='status',
            field=models.TextField(blank=True),
        ),
    ]
